#language: python
services:
  - docker

before_install:
  - pip install ansible
  - ansible-galaxy install sky_joker.ansible_vmware_govcsim_provisioner -p roles

jobs:
  include:
    - stage: python tool test
      name: python test
      python: 3.6
      script:
        - ls
    - stage: go tool test
      name: go test
      go: 1.11.1
      script:
        - ls
