services:
  - docker

before_install:
  - sudo pip install ansible docker-compose
  - ansible-galaxy install sky_joker.ansible_vmware_govcsim_provisioner -p roles
  - ansible-playbook vcsim_provisioning.yml
  - if [ -n "$POWERSHELL" ]; then sudo -s source powershell/setup.sh ; fi

jobs:
  include:
    - stage: tool test
      name: python test
      language: python
      python: 3.6
      script:
        - pip install pyvmomi
        - python python/get-vm.py
    - name: go test
      language: go
      go: 1.11.1
      script:
        - go run go/get-vm.go
    - name: ruby test
      language: ruby
      rvm: 2.6.4
      script:
        - gem install rbvmomi
        - ruby ruby/get-vm.rb
    - name: powershell test
      env: POWERSHELL=yes
      script:
        - pwsh powershell/get-vm.ps1
